version: '3.3'

services:
  db:
    container_name: postgres_container
    image: postgres:12.0-alpine   
    environment:
       - POSTGRES_DB=ez_api_db
       - POSTGRES_USER=ez_api
       - POSTGRES_PASSWORD=somepwd123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data/
    networks:
      - postgres
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - "PGADMIN_DEFAULT_EMAIL=tech@arabeasy.com"
      - "PGADMIN_DEFAULT_PASSWORD=1234"
      - "PGADMIN_LISTEN_PORT=80"
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin-data"
    restart: unless-stopped


networks:
  postgres:
    driver: bridge


volumes:
 postgres_data_2:
 pgadmin-data:
